Toggle visual of bark,
BeccaFi/InstaPups---Frontend pull request #18
Opened 2023-04-15 08:23 UTC by Darkshiira

maping comment correctly

2023-04-15 23:06 UTC, Shinyn commented on instapups/src/Modules/Post.js
> +
Could be a one-liner with the ternary operator.

2023-04-15 23:19 UTC, Shinyn commented on instapups/src/Modules/Post.js
> +              {/* <img src={} alt= {username}/> */}
Why is this commented out?

2023-04-15 23:22 UTC, Shinyn requested changes
If you're still working on code it would help if you left a comment on why some code is commented out so I know what I am looking at. Will request some changes, other than that it looks good.

2023-04-16 08:51 UTC, Darkshiira commented on instapups/src/Modules/Post.js
> +              {/* <img src={} alt= {username}/> */}
Because the url is not implemented in the database-yet, and the comment endpoint isnt done yet! 😄

2023-04-16 08:52 UTC, Darkshiira commented on instapups/src/Modules/Post.js
> +
AH! Didn't know that, thank you!

2023-04-17 00:18 UTC, merged