Logout functionality implemented
BeccaFi/InstaPups---Frontend pull request #19
Opened 2023-04-15 23:01 UTC by Shinyn

Logout button works, my prettier made some ugly changes to the code, sorry about that.

2023-04-16 08:57 UTC, Darkshiira requested changes
I dont know about the others, But I would like the logout to redirect to home page? 
Let's have a discussion about it!

2023-04-16 08:57 UTC, Darkshiira commented on instapups/src/Modules/Logout.jsx
> +    window.location.reload();
Shouldnt it be redirected to login-page tho?
And cool way of Logout, I acctually didnt know about this way!

2023-04-17 00:23 UTC, Shinyn commented on instapups/src/Modules/Logout.jsx
> +    window.location.reload();
Yes, you're correct, an oversight on my part. Didn't realise it untill after i deleted the branch though D:
If you merge it I will make the changes on a small branch and push it up :)

2023-04-17 04:05 UTC, Darkshiira approved these changes

2023-04-17 04:05 UTC, merged